### PR TITLE
Add Blend new grad positions

### PR DESCRIPTION
**Pull request by perryh**
Some extraneous whitespace removed by my text editor.

### CODE REVIEW

**Comment by kyawzazaw** [comment]
Blend is 2021 graduates

**Comment by danerwilliams** [comment]
@kyawzazaw where do you see that it's 2021?

**Comment by kyawzazaw** [comment]
@danerwilliams 

In the job posting link:

`Who you are: 
Currently enrolled in an accredited university graduating in 2021
Excellent coding, problem solving, and debugging skills
Solid understanding of computer science fundamentals
Excellent communication skil`

**Comment by perryh** [comment]
Thanks. That is most likely a mistake. I'll ask someone to update the copy tomorrow. We are definitely not hiring 2021 new grads anymore.

**Comment by perryh** [comment]
Ah, the link is for new grads starting work this year. There are still positions available.

Our 2022 new grads positions aren't available yet. I'll make another PR when they becomes available.

**Pull request closed without merging**
